from onesecmail.__version__ import __author__  # noqa: F401
from onesecmail.__version__ import __author_email__  # noqa: F401
from onesecmail.__version__ import __copyright__  # noqa: F401
from onesecmail.__version__ import __description__  # noqa: F401
from onesecmail.__version__ import __license__  # noqa: F401
from onesecmail.__version__ import __title__  # noqa: F401
from onesecmail.__version__ import __url__  # noqa: F401
from onesecmail.__version__ import __version__  # noqa: F401
from onesecmail.mail import OneSecMail  # noqa: F401
