from onesecmail.__version__ import __author__
from onesecmail.__version__ import __author_email__
from onesecmail.__version__ import __copyright__
from onesecmail.__version__ import __description__
from onesecmail.__version__ import __license__
from onesecmail.__version__ import __title__
from onesecmail.__version__ import __url__
from onesecmail.__version__ import __version__
from onesecmail.mail import OneSecMail
